openapi: 3.0.1
info:
  title: Cart API
  description: API para la gestión de carritos de compra
  version: 1.0.0
paths:
  /api/carts:
    post:
      summary: Crear un nuevo carrito
      tags:
        - Cart
      responses:
        "200":
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "500":
          description: Error del servidor

  /api/carts/{cid}:
    get:
      summary: Obtener un carrito por ID
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        "200":
          description: Carrito obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "404":
          description: Carrito no encontrado
        "500":
          description: Error del servidor
    put:
      summary: Actualizar el carrito con un arreglo de productos
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    $ref: "#/components/schemas/ProductInCart"
      responses:
        "200":
          description: Carrito actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "500":
          description: Error del servidor
    delete:
      summary: Eliminar todos los productos de un carrito específico
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        "200":
          description: Carrito vaciado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "500":
          description: Error del servidor

  /api/carts/{cid}/products/{pid}:
    post:
      summary: Agregar un producto a un carrito específico
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        "200":
          description: Producto agregado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "500":
          description: Error del servidor
    delete:
      summary: Eliminar un producto de un carrito específico
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        "200":
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "404":
          description: Producto no encontrado en el carrito
        "500":
          description: Error del servidor

  /api/carts/{cid}/products/{pid}/quantity:
    put:
      summary: Actualizar la cantidad de un producto en un carrito específico
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        "200":
          description: Cantidad actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "404":
          description: Producto no encontrado en el carrito
        "500":
          description: Error del servidor

  /api/carts/{cid}/purchase:
    post:
      summary: Completar la compra de un carrito
      tags:
        - Cart
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        "200":
          description: Compra completada exitosamente
        "500":
          description: Error del servidor

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
        products:
          type: array
          items:
            $ref: "#/components/schemas/ProductInCart"
    ProductInCart:
      type: object
      properties:
        product:
          type: object
          properties:
            _id:
              type: string
            title:
              type: string
            price:
              type: number
        quantity:
          type: integer
          description: Cantidad del producto en el carrito
